# Generated by Django 5.1.1 on 2025-02-27 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseinfo",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1, "年龄必须大于或等于1"),
                    django.core.validators.MaxValueValidator(100, "年龄必须小于或等于100"),
                ],
                verbose_name="年龄",
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="姓名"
            ),
        ),
    ]
