# Generated by Django 5.1.1 on 2025-02-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0002_alter_baseinfo_age_alter_baseinfo_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseinfo",
            name="diagnosis_date",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="诊断日期"
            ),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="screen_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="筛查日期"),
        ),
    ]
