# Generated by Django 5.1.1 on 2025-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0003_baseinfo_diagnosis_date_alter_baseinfo_screen_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseinfo",
            name="screen_date",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="筛查日期"
            ),
        ),
    ]
